### ISSUE TITLE
 Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "099dd09dac017ce8479a1f5e9552fa15506efbd821122d17f763ccd13b7d2ab4": [default/virt-launcher-cbip-1-1-2bh8l:sriov-net4-cbip-1]: error adding container to network "sriov-net4-cbip-1": failed to set up pod interface "net8" from the device "sfp_5": failed to set netlink MAC address to 00:94:a1:ce:fe:0c: resource temporarily unavailable

### ISSUE THREAD

**Issue by mattavamsi2** [k8snetworkplumbingwg/sriov-network-device-plugin#559] opened 2024-05-20 04:41 UTC
Hi, We are trying to launch a VM with the intel based ice driver created VF, But we are getting this error upon launching VM using qemu. But all the resources are free to use. 
And I am not able to figure out what is happening with ice driver side also. I am attaching logs in this issue, If any one aware of this, Help us to understand more. 

```
[root@appliance-1:Active] ~ # kubectl get pods -A
...
default       f5-resource-manager-9cgd6                 1/1     Running    0          4d14h
default       virt-launcher-cbip-1-1-2bh8l              0/1     Init:0/1   0          3d19h

[root@appliance-1:Active] ~ # kubectl get events
LAST SEEN   TYPE      REASON                   OBJECT                             MESSAGE
3s          Warning   FailedCreatePodSandBox   pod/virt-launcher-cbip-1-1-2bh8l   (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "8f08fe3e20cf48ae3893c6e9288e57ece3b3c98ce46ee7922f7232012d1206dd": [default/virt-launcher-cbip-1-1-2bh8l:sriov-net4-cbip-1]: error adding container to network "sriov-net4-cbip-1": failed to set up pod interface "net8" from the device "sfp_5": failed to set netlink MAC address to 00:94:a1:ce:fe:0c: resource temporarily unavailable

```

iavf version: 4.3.19
ice version: ice-1.7.16-1
sriov-dp version: v3.4.0

[logs.txt](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/files/15372746/logs.txt)

Thanks.

**Comment by zeeke** [comment] 2024-05-20 07:36
Hi @mattavamsi2 , the problem is likely to be around the sriov-cni . Can you post the version of that component? 
If you're using the sriov-network-operator and  SriovNetwork resource, can you set the `.Spec.LogLevel` field to `debug` ?

**Comment by SchSeba** [comment] 2024-06-02 12:49
Hi @mattavamsi2 can you please provide the info here?

**Comment by SchSeba** [comment] 2024-12-31 19:05
closing

**Closed by SchSeba** 2024-12-31 19:05 UTC
