### ISSUE TITLE
Windows virtual machine cannot use the network card added by sriov

### ISSUE THREAD

**Issue by newhuangchuan** [k8snetworkplumbingwg/sriov-network-device-plugin#393] opened 2021-10-27 01:47 UTC
### What happened?
![image](https://user-images.githubusercontent.com/53457306/138985358-35aef455-d57d-48e4-a952-4cf6f6fb3aee.png)
When I install the virtual machine using sriov's network, the virtual machine installed on the Linux system can normally recognize my second network card and load the IP address I set, but after the Windows 10 system is installed, only the first cni network card can be used , The second network card can be found in the device manager, but the relevant network card driver cannot be added through virtio. Excuse me, how to solve this change?
### What did you expect to happen?
What I want to see is that the virtual machine of the Windows 10 system can also load two network cards.
### What are the minimal steps needed to reproduce the bug?
1
### Anything else we need to know?
My underlying kubernetes cluster is deployed in a Linux system. I don’t know if it’s because of the incompatibility between PCI Express Linux and Windows, or the driver problem?
### Component Versions
Please fill in the below table with the version numbers of components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |<v3.3.1>|
|SR-IOV CNI Plugin            |<v2.6.1>|
|Multus                       |<v3.7.1>|
|Kubernetes                   |<v1.18.5>| 
|OS                           |<ubuntu>|

### Config Files
Config file locations may be config dependent.
```
$ cat vm.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winhd-english
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: hostpath
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: windows-english-1
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: windows-english-1
    spec:
      domain:
        cpu:
          model: host-passthrough
          sockets: 2
          cores: 4
          threads: 2
          dedicatedCpuPlacement: true
        resources: 
          requests: 
            intel.com/intel_sriov_dpdk: '1'
            memory: 8G
          limits: 
            intel.com/intel_sriov_dpdk: '1'
            memory: 8G
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - bootOrder: 2
            disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
          interfaces: 
          - name: default 
            bridge: {}
          - name: sriov-net1
            sriov: {}
          rng: {}
        machine:
          type: q35
      networks: 
      - name: default
        pod: {}
      - multus: 
          networkName: default/sriov-net1
        name: sriov-net1
      terminationGracePeriodSeconds: 0
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: windows-english-iso
      - name: harddrive
        persistentVolumeClaim:
          claimName: winhd-english
      - containerDisk:
          image: kubevirt/virtio-container-disk
          imagePullPolicy: Never
        name: virtiocontainerdisk
```
##### Device pool config file location (Try '/etc/pcidp/config.json')
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "intel_sriov_netdevice",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["37cd", "10ed", "1889"],
                    "drivers": ["i40evf", "iavf", "ixgbevf"]
                }
            },
            {
                "resourceName": "intel_sriov_dpdk",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["37cd", "10ed", "1889"],
                    "drivers": ["vfio-pci"],
                    "pciAddresses": ["0000:60:06.0","0000:60:06.1","0000:60:06.2","0000:60:06.3","0000:60:06.4","0000:60:06.5","0000:60:06.6","0000:60:06.7"]
                }
            }
        ]
    }
```
##### SR-IOV Network Device Plugin Logs (use `kubectl logs $PODNAME`)
```
[uos@k8s-master kubevirt]$ kubectl  -n kube-system logs kube-sriov-device-plugin-amd64-j8df7
I1026 02:33:31.189394       1 manager.go:52] Using Kubelet Plugin Registry Mode
I1026 02:33:31.190090       1 main.go:44] resource manager reading configs
I1026 02:33:31.190237       1 manager.go:86] raw ResourceList: {
    "resourceList": [{
            "resourceName": "intel_sriov_netdevice",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["37cd", "10ed", "1889"],
                "drivers": ["i40evf", "iavf", "ixgbevf"]
            }
        },
        {
            "resourceName": "intel_sriov_dpdk",
            "selectors": {
                "vendors": ["8086"],
                "devices": ["37cd", "10ed", "1889"],
                "drivers": ["vfio-pci"],
                "pciAddresses": ["0000:60:06.0","0000:60:06.1","0000:60:06.2","0000:60:06.3","0000:60:06.4","0000:60:06.5","0000:60:06.6","0000:60:06.7"]
            }
        }
    ]
}
I1026 02:33:31.190290       1 factory.go:168] net device selector for resource intel_sriov_netdevice is &{DeviceSelectors:{Vendors:[8086] Devices:[37cd 10ed 1889] Drivers:[i40evf iavf ixgbevf] PciAddresses:[]} PfNames:[] RootDevices:[] LinkTypes:[] DDPProfiles:[] IsRdma:false NeedVhostNet:false}
I1026 02:33:31.190334       1 factory.go:168] net device selector for resource intel_sriov_dpdk is &{DeviceSelectors:{Vendors:[8086] Devices:[37cd 10ed 1889] Drivers:[vfio-pci] PciAddresses:[0000:60:06.0 0000:60:06.1 0000:60:06.2 0000:60:06.3 0000:60:06.4 0000:60:06.5 0000:60:06.6 0000:60:06.7]} PfNames:[] RootDevices:[] LinkTypes:[] DDPProfiles:[] IsRdma:false NeedVhostNet:false}
I1026 02:33:31.190349       1 manager.go:106] unmarshalled ResourceList: [{ResourcePrefix: ResourceName:intel_sriov_netdevice DeviceType:netDevice Selectors:0xc00000ccc0 SelectorObj:0xc0003ca1a0} {ResourcePrefix: ResourceName:intel_sriov_dpdk DeviceType:netDevice Selectors:0xc00000ccd8 SelectorObj:0xc0003ca4e0}]
I1026 02:33:31.190406       1 manager.go:193] validating resource name "intel.com/intel_sriov_netdevice"
I1026 02:33:31.190426       1 manager.go:193] validating resource name "intel.com/intel_sriov_dpdk"
I1026 02:33:31.190431       1 main.go:60] Discovering host devices
I1026 02:33:31.282616       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:00.0 02              Intel Corporation       Ethernet Connection X722 for 1GbE       
I1026 02:33:31.374256       1 netDeviceProvider.go:116] excluding interface eno1:  default route found: {Ifindex: 2 Dst: <nil> Src: <nil> Gw: 10.10.82.1 Flags: [] Table: 254}
I1026 02:33:31.374348       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:00.1 02              Intel Corporation       Ethernet Connection X722 for 1GbE       
I1026 02:33:31.374591       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.0 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1026 02:33:31.374623       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.1 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1026 02:33:31.374643       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.2 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1026 02:33:31.374672       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.3 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1026 02:33:31.374691       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.4 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1026 02:33:31.374722       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.5 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1026 02:33:31.374747       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.6 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1026 02:33:31.374770       1 netDeviceProvider.go:78] netdevice AddTargetDevices(): device found: 0000:60:06.7 02              Intel Corporation       Ethernet Virtual Function 700 Series    
I1026 02:33:31.374819       1 main.go:66] Initializing resource servers
I1026 02:33:31.374829       1 manager.go:112] number of config: 2
I1026 02:33:31.374834       1 manager.go:115] 
I1026 02:33:31.374837       1 manager.go:116] Creating new ResourcePool: intel_sriov_netdevice
I1026 02:33:31.374840       1 manager.go:117] DeviceType: netDevice
I1026 02:33:31.377212       1 manager.go:130] no devices in device pool, skipping creating resource server for intel_sriov_netdevice
I1026 02:33:31.377221       1 manager.go:115] 
I1026 02:33:31.377223       1 manager.go:116] Creating new ResourcePool: intel_sriov_dpdk
I1026 02:33:31.377227       1 manager.go:117] DeviceType: netDevice
I1026 02:33:31.379361       1 factory.go:108] device added: [pciAddr: 0000:60:06.0, vendor: 8086, device: 37cd, driver: vfio-pci]
I1026 02:33:31.379370       1 factory.go:108] device added: [pciAddr: 0000:60:06.1, vendor: 8086, device: 37cd, driver: vfio-pci]
I1026 02:33:31.379373       1 factory.go:108] device added: [pciAddr: 0000:60:06.2, vendor: 8086, device: 37cd, driver: vfio-pci]
I1026 02:33:31.379376       1 factory.go:108] device added: [pciAddr: 0000:60:06.3, vendor: 8086, device: 37cd, driver: vfio-pci]
I1026 02:33:31.379378       1 factory.go:108] device added: [pciAddr: 0000:60:06.4, vendor: 8086, device: 37cd, driver: vfio-pci]
I1026 02:33:31.379381       1 factory.go:108] device added: [pciAddr: 0000:60:06.5, vendor: 8086, device: 37cd, driver: vfio-pci]
I1026 02:33:31.379384       1 factory.go:108] device added: [pciAddr: 0000:60:06.6, vendor: 8086, device: 37cd, driver: vfio-pci]
I1026 02:33:31.379387       1 factory.go:108] device added: [pciAddr: 0000:60:06.7, vendor: 8086, device: 37cd, driver: vfio-pci]
I1026 02:33:31.379402       1 manager.go:145] New resource server is created for intel_sriov_dpdk ResourcePool
I1026 02:33:31.379419       1 main.go:72] Starting all servers...
I1026 02:33:31.379715       1 server.go:196] starting intel_sriov_dpdk device plugin endpoint at: intel.com_intel_sriov_dpdk.sock
I1026 02:33:31.380225       1 server.go:222] intel_sriov_dpdk device plugin endpoint started serving
I1026 02:33:31.380245       1 main.go:77] All servers started.
I1026 02:33:31.380250       1 main.go:78] Listening for term signals
I1026 02:33:31.812645       1 server.go:106] Plugin: intel.com_intel_sriov_dpdk.sock gets registered successfully at Kubelet
I1026 02:33:31.812656       1 server.go:131] ListAndWatch(intel_sriov_dpdk) invoked
I1026 02:33:31.812666       1 server.go:139] ListAndWatch(intel_sriov_dpdk): send devices &ListAndWatchResponse{Devices:[]*Device{&Device{ID:0000:60:06.0,Health:Healthy,Topology:&TopologyInfo{Nodes:[]*NUMANode{&NUMANode{ID:0,},},},},&Device{ID:0000:60:06.1,Health:Healthy,Topology:&TopologyInfo{Nodes:[]*NUMANode{&NUMANode{ID:0,},},},},&Device{ID:0000:60:06.2,Health:Healthy,Topology:&TopologyInfo{Nodes:[]*NUMANode{&NUMANode{ID:0,},},},},&Device{ID:0000:60:06.3,Health:Healthy,Topology:&TopologyInfo{Nodes:[]*NUMANode{&NUMANode{ID:0,},},},},&Device{ID:0000:60:06.4,Health:Healthy,Topology:&TopologyInfo{Nodes:[]*NUMANode{&NUMANode{ID:0,},},},},&Device{ID:0000:60:06.5,Health:Healthy,Topology:&TopologyInfo{Nodes:[]*NUMANode{&NUMANode{ID:0,},},},},&Device{ID:0000:60:06.6,Health:Healthy,Topology:&TopologyInfo{Nodes:[]*NUMANode{&NUMANode{ID:0,},},},},&Device{ID:0000:60:06.7,Health:Healthy,Topology:&TopologyInfo{Nodes:[]*NUMANode{&NUMANode{ID:0,},},},},},}
I1026 02:58:27.497964       1 server.go:115] Allocate() called with &AllocateRequest{ContainerRequests:[]*ContainerAllocateRequest{&ContainerAllocateRequest{DevicesIDs:[0000:60:06.1 0000:60:06.2],},},}
I1026 02:58:27.498053       1 netResourcePool.go:50] GetDeviceSpecs(): for devices: [0000:60:06.1 0000:60:06.2]
I1026 02:58:27.498235       1 pool_stub.go:97] GetEnvs(): for devices: [0000:60:06.1 0000:60:06.2]
I1026 02:58:27.498244       1 pool_stub.go:113] GetMounts(): for devices: [0000:60:06.1 0000:60:06.2]
I1026 02:58:27.498250       1 server.go:124] AllocateResponse send: &AllocateResponse{ContainerResponses:[]*ContainerAllocateResponse{&ContainerAllocateResponse{Envs:map[string]string{PCIDEVICE_INTEL_COM_INTEL_SRIOV_DPDK: 0000:60:06.1,0000:60:06.2,},Mounts:[]*Mount{},Devices:[]*DeviceSpec{&DeviceSpec{ContainerPath:/dev/vfio/vfio,HostPath:/dev/vfio/vfio,Permissions:mrw,},&DeviceSpec{ContainerPath:/dev/vfio/75,HostPath:/dev/vfio/75,Permissions:mrw,},&DeviceSpec{ContainerPath:/dev/vfio/76,HostPath:/dev/vfio/76,Permissions:mrw,},},Annotations:map[string]string{},},},}
I1026 08:39:22.525398       1 server.go:115] Allocate() called with &AllocateRequest{ContainerRequests:[]*ContainerAllocateRequest{&ContainerAllocateRequest{DevicesIDs:[0000:60:06.0 0000:60:06.1],},},}
I1026 08:39:22.525473       1 netResourcePool.go:50] GetDeviceSpecs(): for devices: [0000:60:06.0 0000:60:06.1]
I1026 08:39:22.525593       1 pool_stub.go:97] GetEnvs(): for devices: [0000:60:06.0 0000:60:06.1]
I1026 08:39:22.525601       1 pool_stub.go:113] GetMounts(): for devices: [0000:60:06.0 0000:60:06.1]
I1026 08:39:22.525606       1 server.go:124] AllocateResponse send: &AllocateResponse{ContainerResponses:[]*ContainerAllocateResponse{&ContainerAllocateResponse{Envs:map[string]string{PCIDEVICE_INTEL_COM_INTEL_SRIOV_DPDK: 0000:60:06.0,0000:60:06.1,},Mounts:[]*Mount{},Devices:[]*DeviceSpec{&DeviceSpec{ContainerPath:/dev/vfio/vfio,HostPath:/dev/vfio/vfio,Permissions:mrw,},&DeviceSpec{ContainerPath:/dev/vfio/74,HostPath:/dev/vfio/74,Permissions:mrw,},&DeviceSpec{ContainerPath:/dev/vfio/75,HostPath:/dev/vfio/75,Permissions:mrw,},},Annotations:map[string]string{},},},}
I1026 09:03:53.961664       1 server.go:115] Allocate() called with &AllocateRequest{ContainerRequests:[]*ContainerAllocateRequest{&ContainerAllocateRequest{DevicesIDs:[0000:60:06.3 0000:60:06.4],},},}
I1026 09:03:53.961745       1 netResourcePool.go:50] GetDeviceSpecs(): for devices: [0000:60:06.3 0000:60:06.4]
I1026 09:03:53.961896       1 pool_stub.go:97] GetEnvs(): for devices: [0000:60:06.3 0000:60:06.4]
I1026 09:03:53.961905       1 pool_stub.go:113] GetMounts(): for devices: [0000:60:06.3 0000:60:06.4]
I1026 09:03:53.961910       1 server.go:124] AllocateResponse send: &AllocateResponse{ContainerResponses:[]*ContainerAllocateResponse{&ContainerAllocateResponse{Envs:map[string]string{PCIDEVICE_INTEL_COM_INTEL_SRIOV_DPDK: 0000:60:06.3,0000:60:06.4,},Mounts:[]*Mount{},Devices:[]*DeviceSpec{&DeviceSpec{ContainerPath:/dev/vfio/vfio,HostPath:/dev/vfio/vfio,Permissions:mrw,},&DeviceSpec{ContainerPath:/dev/vfio/77,HostPath:/dev/vfio/77,Permissions:mrw,},&DeviceSpec{ContainerPath:/dev/vfio/78,HostPath:/dev/vfio/78,Permissions:mrw,},},Annotations:map[string]string{},},},}
I1027 01:27:41.939659       1 server.go:115] Allocate() called with &AllocateRequest{ContainerRequests:[]*ContainerAllocateRequest{&ContainerAllocateRequest{DevicesIDs:[0000:60:06.2 0000:60:06.3],},},}
I1027 01:27:41.939729       1 netResourcePool.go:50] GetDeviceSpecs(): for devices: [0000:60:06.2 0000:60:06.3]
I1027 01:27:41.939877       1 pool_stub.go:97] GetEnvs(): for devices: [0000:60:06.2 0000:60:06.3]
I1027 01:27:41.939887       1 pool_stub.go:113] GetMounts(): for devices: [0000:60:06.2 0000:60:06.3]
I1027 01:27:41.939892       1 server.go:124] AllocateResponse send: &AllocateResponse{ContainerResponses:[]*ContainerAllocateResponse{&ContainerAllocateResponse{Envs:map[string]string{PCIDEVICE_INTEL_COM_INTEL_SRIOV_DPDK: 0000:60:06.2,0000:60:06.3,},Mounts:[]*Mount{},Devices:[]*DeviceSpec{&DeviceSpec{ContainerPath:/dev/vfio/vfio,HostPath:/dev/vfio/vfio,Permissions:mrw,},&DeviceSpec{ContainerPath:/dev/vfio/76,HostPath:/dev/vfio/76,Permissions:mrw,},&DeviceSpec{ContainerPath:/dev/vfio/77,HostPath:/dev/vfio/77,Permissions:mrw,},},Annotations:map[string]string{},},},}

```

**Comment by adrianchiris** [comment] 2022-01-19 14:56
Going over the logs i do not see issues with sriov-network-device plugin. 

maybe issue related to kubevirt ?

**Comment by SchSeba** [comment] 2022-01-19 16:55
Is this a duplicate of https://github.com/kubevirt/kubevirt/issues/6671 ?

**Comment by EdDev** [comment] 2022-01-19 16:55
This seems to be a duplicate of https://github.com/kubevirt/kubevirt/issues/6671.
Looks to me line a windows OS problem which unfortunately have nothing special to add beyond what was suggested in the original issue (to try and install the proper drivers).

**Comment by SchSeba** [comment] 2022-01-20 09:47
@newhuangchuan can we close the issue here?

**Comment by adrianchiris** [comment] 2022-03-13 09:34
closing this issue as it does not seem to be related to sriov-network-device-plugin.

**Closed by adrianchiris** 2022-03-13 09:34 UTC
